/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface FrameData {
  width: number
  height: number
  timestampMs: number
  buffer: Buffer
  mouseX?: number
  mouseY?: number
  originX: number
  originY: number
}
export interface DesktopSource {
  id: string
  name: string
  thumbnail?: string
  sourceType: string
}
export interface RecordingOptions {
  targetId: string
  captureType: string
  includeCursor: boolean
  frameRate: number
  fileName?: string
}
export declare function listSources(): Array<DesktopSource>
export declare function startCapture(options: RecordingOptions): void
export declare function stopCapture(): void
export declare function pollFrame(): Promise<FrameData | null>
export interface MouseEventRecord {
  timestampMs: number
  x: number
  y: number
  normalizedX: number
  normalizedY: number
  buttonState: string
  isPressed: boolean
  cursorShape: string
}
export declare function getRecordingMouseEvents(): Array<MouseEventRecord>
export declare function clearRecordingMouseEvents(): void
export declare function getCurrentMousePosition(): MouseEventRecord | null
export declare function startRecording(options: RecordingOptions): string
export declare function stopRecording(): string
