/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface FrameData {
  width: number
  height: number
  timestampMs: number
  buffer: Buffer
  mouseX?: number
  mouseY?: number
  originX: number
  originY: number
}
export interface DesktopSource {
  id: string
  name: string
  thumbnail?: string
  sourceType: string
}
export interface RecordingOptions {
  targetId: string
  captureType: string
  includeCursor: boolean
  frameRate: number
  fileName?: string
}
export declare function listSources(): Array<DesktopSource>
export declare function startCapture(options: RecordingOptions): void
export declare function stopCapture(): void
export declare function pollFrame(): Promise<FrameData | null>
export interface MouseEventRecord {
  timestampMs: number
  x: number
  y: number
  normalizedX: number
  normalizedY: number
  buttonState: string
  isPressed: boolean
  cursorShape: string
}
export declare function getRecordingMouseEvents(): Array<MouseEventRecord>
export declare function clearRecordingMouseEvents(): void
export declare function getCurrentMousePosition(): MouseEventRecord | null
export declare function startRecording(options: RecordingOptions): string
export declare function stopRecording(): string
export const enum EngineType {
  Whisper = 'Whisper',
  Parakeet = 'Parakeet'
}
export interface ModelInfo {
  id: string
  name: string
  description: string
  filename: string
  url?: string
  sizeMb: number
  isDownloaded: boolean
  isDownloading: boolean
  partialSize: number
  isDirectory: boolean
  engineType: string
  accuracyScore: number
  speedScore: number
}
export interface DownloadProgress {
  modelId: string
  downloaded: number
  total: number
  percentage: number
}
export declare function modelListAvailable(): Array<ModelInfo>
export declare function modelGetInfo(modelId: string): ModelInfo | null
export declare function modelGetPath(modelId: string): string
export declare function modelDownload(modelId: string): boolean
export declare function modelCancelDownload(modelId: string): boolean
export declare function modelDelete(modelId: string): boolean
export declare function modelRefreshStatus(): void
export interface TranscriptSegment {
  startMs: number
  endMs: number
  text: string
  speaker?: string
}
export interface Transcript {
  provider: string
  language?: string
  segments: Array<TranscriptSegment>
  raw?: string
}
export interface SubmitTranscriptionRequest {
  provider: string
  apiBaseUrl?: string
  apiKey?: string
  audioUrl?: string
  filePath?: string
  model?: string
  languageHints?: Array<string>
  enableLanguageIdentification?: boolean
  enableSpeakerDiarization?: boolean
  clientReferenceId?: string
}
export interface TranscriptionJobInfo {
  jobId: string
  provider: string
  status: string
}
export interface TranscriptionJobSnapshot {
  jobId: string
  provider: string
  status: string
  errorMessage?: string
  progress?: number
}
export declare function transcriptionListProviders(): Array<string>
export declare function transcriptionCancel(jobId: string): boolean
export declare function transcriptionGetJob(jobId: string): TranscriptionJobSnapshot | null
export declare function transcriptionGetResult(jobId: string): Transcript | null
export declare function transcriptionSubmit(req: SubmitTranscriptionRequest): TranscriptionJobInfo
